### ISSUE TITLE
OPAM does not install the latest version of a software

### ISSUE THREAD

**Issue by vbmithr** [ocaml/opam#1329]
```
[vb@nerenyi ~/code/opam-repository/packages/ocaml-markdown/ocaml-markdown.0.1.1]% opam info ocaml-markdown        
             package: ocaml-markdown
             version: 9999
             depends: ocamlfind & batteries & sexplib & ounit & tyxml
   installed-version: 
  available-versions: 0.1.0, 0.1.1, 9999
         description: 
[vb@nerenyi ~/code/opam-repository/packages/ocaml-markdown/ocaml-markdown.0.1.1]% opam install ocaml-markdown     
The following actions will be performed:
 - downgrade extlib from 1.6.1 to 1.5.3            [required by ocaml-markdown]
 - install   ocaml-markdown.0.1.1
 - recompile extprot.1.1.1                         [uses extlib]
 - recompile cudf.0.6.3                            [uses extlib]
=== 1 to install | 2 to reinstall | 1 to downgrade ===
```
