### ISSUE TITLE
OPAM does not honor optional packages

### ISSUE THREAD

**Issue by vbmithr** [ocaml/opam#1629]
```
[vb@nerenyi ~/code/ocaml-websocket]% opam install conduit                                                  
The following actions will be performed:                                                                   
 - install   ssl.0.4.7                             [required by conduit]                                   
 - recompile lwt.2.4.5                             [uses ssl]                                              
 - recompile tuntap.1.0.0                          [uses lwt]                                              
 - recompile lambda-term.1.6                       [uses lwt]                                              
 - recompile cstruct.1.4.0                         [uses lwt]                                              
 - install   conduit.0.5.1                                                                                 
 - recompile utop.1.14                             [uses lwt]                                              
 - recompile nocrypto.0.1.0*                       [uses cstruct]                                          
 - recompile asn1-combinators.0.0.1*               [uses cstruct]                                          
 - recompile x509.0.1.0*                           [uses cstruct]                                          
 - recompile tls.0.1.0*                            [uses lwt]                                              
=== 2 to install | 9 to reinstall ===                                                                      
Do you want to continue ? [Y/n] n                                                                          
[vb@nerenyi ~/code/ocaml-websocket]% opam info conduit                                                     
             package: conduit                                                                              
             version: 0.5.1                                                                                
          repository: default                                                                              
        upstream-url: https://github.com/mirage/ocaml-conduit/archive/v0.5.1.tar.gz                        
       upstream-kind: http                                                                                 
   upstream-checksum: 8b9f180f3f9743d9c6a20dcd0f7d359a                                                     
                tags: org:mirage                                                                           
             depends: ocamlfind & sexplib >= 109.15.00                                                     
             depopts: async | lwt | (lwt & ssl) | async_ssl                                                
   installed-version:                                                                                      
  available-versions: 0.5.0, 0.5.1                                                                         
         description: Network connection library for TCP and SSL   
```

ssl is not required by conduit, it is only optional, yet OPAM wants to install it

Disclaimer: I have this set `OPAMCRITERIA=-count(removed),-notuptodate(solution),-count(down),-count(changed)`
