### ISSUE TITLE
Calling opam commands in Ansible doesn't work well; not sending exit?

### ISSUE THREAD

**Issue by kmahelona** [ocaml/opam#4102]
I'm installing ocaml packages using `opam` via Ansible. I don't know what's wrong... I don't think `opam` returns the correct exit signal or something because Ansible always hangs when trying to do `opam` commands. If I cancel the deploy then run it again it works because the second time around the package already exists and that time `opam` gives the correct exit signal.

For example, this simply runs these commands on the machine:
```
- name: Install ocaml stuff
  become: false
  shell: "{{item}}"
  with_items:
    - opam init -a
    - opam switch create 4.09.0 | true
    - opam install -y dune
```
Even with the auto/yes flags it still hangs. I don't even get a timeout from Ansible which suggests something is still open? I cancel the Ansible deploy, then run this again, and it get success output like,
```
init: User configuration:  ~/.profile is already up-to-date.
switch: [ERROR] There already is an installed switch named 4.09.0 # the | true allows this to work
```

It's likely this is more of an "ansible" thing, but simply running `shell: echo test` works as expected - the command doesn't hang. So I feel like `opam` should do something else once it's finished successfully installing or initialising things.

Thanks,
Keoni.
