### ISSUE TITLE
should `pin-depends` imply `depends` ?

### ISSUE THREAD

**Issue by zapashcanon** [ocaml/opam#5795]
Hi,

I realized that if I have the following `owi.opam` file:

```yml
depends: []
pin-depends: [
  [ "encoding.dev" "git+https://github.com/formalsec/encoding"]
]
```

Then, running `opam install -y ./*.opam --deps-only --with-test` would not install `encoding`.

But if I add it to the `depends` fields:

```yml
depends: [ "encoding" ]
pin-depends: [
  [ "encoding.dev" "git+https://github.com/formalsec/encoding"]
]
```

Then it would be properly installed with the same command.

I'm wondering if there is a reason why a package being present in `pin-depends` does not imply it is part of `depends` ?

Thanks!
